name: tictactoe_betclic
description: "A simple Tic Tac Toe game for iOS and Android."

version: 0.0.1+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  go_router: ^14.6.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen: ^5.4.0
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_lint: ^2.6.2

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/icons/

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true